### ISSUE TITLE
Hitting you up for that NPM module

### ISSUE THREAD

**Issue by MarketingPip** [1j01/ascii-hypercube#4]
I will gladly grab this as NPM module if you are still willing....

By chance too, would it be possible to fill sides with characters? (example white ansi character / aterisk blah blah blah) to give box depth?

**Comment by 1j01** [comment]
Here you go, published `ascii-hypercube@1.0.0`
See the docs on the readme. It uses CommonJS exports (it was a little easier than ESM), and I also threw in a CLI for good measure.

For your other request, if you open another issue with a clearer description and a handcrafted example of the sort of text effect you're wanting, I'll see what I can do.

And of course, let me know if you run into any problems! :)

**Comment by MarketingPip** [comment]
@1j01  - thank you Isaiah! Ideally I am hoping to use this library to make shapes / 3D boxes like the image below!

![image](https://github.com/user-attachments/assets/fc3ba6bd-36da-43c3-a1ec-0e56ff6cfb1d)

So then we can make cool "ascii" signs ;) that are displayed on the front. 

![image](https://github.com/user-attachments/assets/232d2b1f-0c35-4c8a-bda2-38dfe386e4a0)
